export const userSuperTypes = ['Имя', 'Фамилия', 'E-mail', 'Организация', 'Роль']
export const userTypes = ['Имя', 'Фамилия', 'E-mail', 'Роль']
export const licensesTypes = ['Название', 'Локация', 'Кол-во аккаунтов', 'Дата начала', 'Дата окончания']
export const fileTypes = ['Наименование', 'Формат', 'Вес', 'Дата загрузки']
export const sceneTypes = ['Наименование', 'Количество событий', 'Дата последнего события', 'Организатор']